name: messenger-cli
version: 0.4.0
title: GNUnet Messenger
summary: An interface using ncurses for the Messenger service of GNUnet.
description: |
  The tool messenger-cli is an terminal interface for the GNUnet Messenger service. The goal is to provide private and secure communication between any group of devices.
  
  Chats will generally created as opt-in. So you can decide who may contact you directly and who does not, accepting to a direct chat. Leaving a chat is also always possible.
website:
  - https://git.gnunet.org/messenger-cli.git/about/
contact:
  - gnunet@thejackimonster.de
donation:
  - https://www.gnunet.org/en/ev.html
  - https://liberapay.com/GNUnet-Messenger/
source-code:
  - https://git.gnunet.org/messenger-cli.git/
issues:
  - https://bugs.gnunet.org
license: GPL-3.0-or-later
adopt-info: messenger-cli
base: core24
confinement: strict
grade: stable

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  messenger-cli:
    command: usr/bin/messenger-cli
    plugs:
      - home
      - network
      - network-bind

parts:
  gnunet:
    build-packages:
      - libgcrypt20-dev
      - recutils
      - libjansson-dev
      - libsodium-dev
      - libcurl4-gnutls-dev
      - libidn2-dev
      - libunistring-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - libltdl-dev
      - zlib1g-dev
      - meson
    stage-packages:
      - libgcrypt20
      - recutils
      - libjansson4
      - libsodium23
      - libcurl3t64-gnutls
      - libidn2-0
      - libunistring5
      - libsqlite3-0
      - libmicrohttpd12
      - libgnutls-dane0
      - libunbound8
      - libltdl7
      - zlib1g
    source: https://ftpmirror.gnu.org/gnunet/gnunet-0.25.0.tar.gz
    source-checksum: sha512/5ff3c4ecb79a96721e7cd23042dc93eca314ab95f7d24b096f63398f1b57f134c8d7b2c646eb4b95cc76c63ac0147c369d3119ca2d12e9a01cd74250dc0c3a37
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
  libgnunetchat:
    after: [ gnunet ]
    build-packages:
      - pkg-config
    source: https://ftpmirror.gnu.org/gnunet/libgnunetchat-0.6.0.tar.gz
    source-checksum: sha512/46402752bf6f8a5b9e66fb7863f7b4430bc2679e42df4aeade48d6f60bd6d4d77d2079ea2ef26e72faa399eda9dd2aa485c8897f2e9af55f2258794f47424851
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
  messenger-cli:
    after: [ gnunet, libgnunetchat ]
    build-packages:
      - libncurses-dev
    stage-packages:
      - libncurses6
    source: https://ftpmirror.gnu.org/gnunet/messenger-cli-0.4.0.tar.gz
    source-checksum: sha512/a6971c599eb08bd501572c3ca38a628f6bcf18d22de5f77edff19cf4a29d463247231b69afd4907240a14299b384b99af35c90bf0cfbc02cc7ae2113753fd393
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
